CycleProductionBuildings: TAB Ctrl
	Description: Hotkey-CycleProductionBuildings
	Types: Production
	Contexts: player, spectator

SelectProductionBuilding: TAB
	Description: Hotkey-SelectProductionBuilding
	Types: Production
	Contexts: player

Production01: F1
	Description: Hotkey-Production01
	Types: ProductionSlot
	Contexts: player

Production02: F2
	Description: Hotkey-Production02
	Types: ProductionSlot
	Contexts: player

Production03: F3
	Description: Hotkey-Production03
	Types: ProductionSlot
	Contexts: player

Production04: F4
	Description: Hotkey-Production04
	Types: ProductionSlot
	Contexts: player

Production05: F5
	Description: Hotkey-Production05
	Types: ProductionSlot
	Contexts: player

Production06: F6
	Description: Hotkey-Production06
	Types: ProductionSlot
	Contexts: player

Production07: F7
	Description: Hotkey-Production07
	Types: ProductionSlot
	Contexts: player

Production08: F8
	Description: Hotkey-Production08
	Types: ProductionSlot
	Contexts: player

Production09: F9
	Description: Hotkey-Production09
	Types: ProductionSlot
	Contexts: player

Production10: F10
	Description: Hotkey-Production10
	Types: ProductionSlot
	Contexts: player

Production11: F11
	Description: Hotkey-Production11
	Types: ProductionSlot
	Contexts: player

Production12: F12
	Description: Hotkey-Production12
	Types: ProductionSlot
	Contexts: player

Production13: F1 CTRL
	Description: Hotkey-Production13
	Types: ProductionSlot
	Contexts: player

Production14: F2 CTRL
	Description: Hotkey-Production14
	Types: ProductionSlot
	Contexts: player

Production15: F3 CTRL
	Description: Hotkey-Production15
	Types: ProductionSlot
	Contexts: player

Production16: F4 CTRL
	Description: Hotkey-Production16
	Types: ProductionSlot
	Contexts: player

Production17: F5 CTRL
	Description: Hotkey-Production17
	Types: ProductionSlot
	Contexts: player

Production18: F6 CTRL
	Description: Hotkey-Production18
	Types: ProductionSlot
	Contexts: player

Production19: F7 CTRL
	Description: Hotkey-Production19
	Types: ProductionSlot
	Contexts: player

Production20: F8 CTRL
	Description: Hotkey-Production20
	Types: ProductionSlot
	Contexts: player

Production21: F9 CTRL
	Description: Hotkey-Production21
	Types: ProductionSlot
	Contexts: player

Production22: F10 CTRL
	Description: Hotkey-Production22
	Types: ProductionSlot
	Contexts: player

Production23: F11 CTRL
	Description: Hotkey-Production23
	Types: ProductionSlot
	Contexts: player

Production24: F12 CTRL
	Description: Hotkey-Production24
	Types: ProductionSlot
	Contexts: player
