#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System.Collections.Generic;

namespace OpenRA
{
	// List of keycodes. Duplicated from SDL 2.0.1, with the addition
	// of MOUSE4 and MOUSE5.
	public enum Keycode
	{
		UNKNOWN = 0,
		RETURN = '\r',
		ESCAPE = 27,
		BACKSPACE = '\b',
		TAB = '\t',
		SPACE = ' ',
		EXCLAIM = '!',
		QUOTEDBL = '"',
		HASH = '#',
		PERCENT = '%',
		DOLLAR = '$',
		AMPERSAND = '&',
		QUOTE = '\'',
		LEFTPAREN = '(',
		RIGHTPAREN = ')',
		ASTERISK = '*',
		PLUS = '+',
		COMMA = ',',
		MINUS = '-',
		PERIOD = '.',
		SLASH = '/',
		NUMBER_0 = '0',
		NUMBER_1 = '1',
		NUMBER_2 = '2',
		NUMBER_3 = '3',
		NUMBER_4 = '4',
		NUMBER_5 = '5',
		NUMBER_6 = '6',
		NUMBER_7 = '7',
		NUMBER_8 = '8',
		NUMBER_9 = '9',
		COLON = ':',
		SEMICOLON = ';',
		LESS = '<',
		EQUALS = '=',
		GREATER = '>',
		QUESTION = '?',
		AT = '@',
		LEFTBRACKET = '[',
		BACKSLASH = '\\',
		RIGHTBRACKET = ']',
		CARET = '^',
		UNDERSCORE = '_',
		BACKQUOTE = '`',
		A = 'a',
		B = 'b',
		C = 'c',
		D = 'd',
		E = 'e',
		F = 'f',
		G = 'g',
		H = 'h',
		I = 'i',
		J = 'j',
		K = 'k',
		L = 'l',
		M = 'm',
		N = 'n',
		O = 'o',
		P = 'p',
		Q = 'q',
		R = 'r',
		S = 's',
		T = 't',
		U = 'u',
		V = 'v',
		W = 'w',
		X = 'x',
		Y = 'y',
		Z = 'z',
		CAPSLOCK = 57 | (1 << 30),
		F1 = 58 | (1 << 30),
		F2 = 59 | (1 << 30),
		F3 = 60 | (1 << 30),
		F4 = 61 | (1 << 30),
		F5 = 62 | (1 << 30),
		F6 = 63 | (1 << 30),
		F7 = 64 | (1 << 30),
		F8 = 65 | (1 << 30),
		F9 = 66 | (1 << 30),
		F10 = 67 | (1 << 30),
		F11 = 68 | (1 << 30),
		F12 = 69 | (1 << 30),
		PRINTSCREEN = 70 | (1 << 30),
		SCROLLLOCK = 71 | (1 << 30),
		PAUSE = 72 | (1 << 30),
		INSERT = 73 | (1 << 30),
		HOME = 74 | (1 << 30),
		PAGEUP = 75 | (1 << 30),
		DELETE = 127,
		END = 77 | (1 << 30),
		PAGEDOWN = 78 | (1 << 30),
		RIGHT = 79 | (1 << 30),
		LEFT = 80 | (1 << 30),
		DOWN = 81 | (1 << 30),
		UP = 82 | (1 << 30),
		NUMLOCKCLEAR = 83 | (1 << 30),
		KP_DIVIDE = 84 | (1 << 30),
		KP_MULTIPLY = 85 | (1 << 30),
		KP_MINUS = 86 | (1 << 30),
		KP_PLUS = 87 | (1 << 30),
		KP_ENTER = 88 | (1 << 30),
		KP_1 = 89 | (1 << 30),
		KP_2 = 90 | (1 << 30),
		KP_3 = 91 | (1 << 30),
		KP_4 = 92 | (1 << 30),
		KP_5 = 93 | (1 << 30),
		KP_6 = 94 | (1 << 30),
		KP_7 = 95 | (1 << 30),
		KP_8 = 96 | (1 << 30),
		KP_9 = 97 | (1 << 30),
		KP_0 = 98 | (1 << 30),
		KP_PERIOD = 99 | (1 << 30),
		APPLICATION = 101 | (1 << 30),
		POWER = 102 | (1 << 30),
		KP_EQUALS = 103 | (1 << 30),
		F13 = 104 | (1 << 30),
		F14 = 105 | (1 << 30),
		F15 = 106 | (1 << 30),
		F16 = 107 | (1 << 30),
		F17 = 108 | (1 << 30),
		F18 = 109 | (1 << 30),
		F19 = 110 | (1 << 30),
		F20 = 111 | (1 << 30),
		F21 = 112 | (1 << 30),
		F22 = 113 | (1 << 30),
		F23 = 114 | (1 << 30),
		F24 = 115 | (1 << 30),
		EXECUTE = 116 | (1 << 30),
		HELP = 117 | (1 << 30),
		MENU = 118 | (1 << 30),
		SELECT = 119 | (1 << 30),
		STOP = 120 | (1 << 30),
		AGAIN = 121 | (1 << 30),
		UNDO = 122 | (1 << 30),
		CUT = 123 | (1 << 30),
		COPY = 124 | (1 << 30),
		PASTE = 125 | (1 << 30),
		FIND = 126 | (1 << 30),
		MUTE = 127 | (1 << 30),
		VOLUMEUP = 128 | (1 << 30),
		VOLUMEDOWN = 129 | (1 << 30),
		KP_COMMA = 133 | (1 << 30),
		KP_EQUALSAS400 = 134 | (1 << 30),
		ALTERASE = 153 | (1 << 30),
		SYSREQ = 154 | (1 << 30),
		CANCEL = 155 | (1 << 30),
		CLEAR = 156 | (1 << 30),
		PRIOR = 157 | (1 << 30),
		RETURN2 = 158 | (1 << 30),
		SEPARATOR = 159 | (1 << 30),
		OUT = 160 | (1 << 30),
		OPER = 161 | (1 << 30),
		CLEARAGAIN = 162 | (1 << 30),
		CRSEL = 163 | (1 << 30),
		EXSEL = 164 | (1 << 30),
		KP_00 = 176 | (1 << 30),
		KP_000 = 177 | (1 << 30),
		THOUSANDSSEPARATOR = 178 | (1 << 30),
		DECIMALSEPARATOR = 179 | (1 << 30),
		CURRENCYUNIT = 180 | (1 << 30),
		CURRENCYSUBUNIT = 181 | (1 << 30),
		KP_LEFTPAREN = 182 | (1 << 30),
		KP_RIGHTPAREN = 183 | (1 << 30),
		KP_LEFTBRACE = 184 | (1 << 30),
		KP_RIGHTBRACE = 185 | (1 << 30),
		KP_TAB = 186 | (1 << 30),
		KP_BACKSPACE = 187 | (1 << 30),
		KP_A = 188 | (1 << 30),
		KP_B = 189 | (1 << 30),
		KP_C = 190 | (1 << 30),
		KP_D = 191 | (1 << 30),
		KP_E = 192 | (1 << 30),
		KP_F = 193 | (1 << 30),
		KP_XOR = 194 | (1 << 30),
		KP_POWER = 195 | (1 << 30),
		KP_PERCENT = 196 | (1 << 30),
		KP_LESS = 197 | (1 << 30),
		KP_GREATER = 198 | (1 << 30),
		KP_AMPERSAND = 199 | (1 << 30),
		KP_DBLAMPERSAND = 200 | (1 << 30),
		KP_VERTICALBAR = 201 | (1 << 30),
		KP_DBLVERTICALBAR = 202 | (1 << 30),
		KP_COLON = 203 | (1 << 30),
		KP_HASH = 204 | (1 << 30),
		KP_SPACE = 205 | (1 << 30),
		KP_AT = 206 | (1 << 30),
		KP_EXCLAM = 207 | (1 << 30),
		KP_MEMSTORE = 208 | (1 << 30),
		KP_MEMRECALL = 209 | (1 << 30),
		KP_MEMCLEAR = 210 | (1 << 30),
		KP_MEMADD = 211 | (1 << 30),
		KP_MEMSUBTRACT = 212 | (1 << 30),
		KP_MEMMULTIPLY = 213 | (1 << 30),
		KP_MEMDIVIDE = 214 | (1 << 30),
		KP_PLUSMINUS = 215 | (1 << 30),
		KP_CLEAR = 216 | (1 << 30),
		KP_CLEARENTRY = 217 | (1 << 30),
		KP_BINARY = 218 | (1 << 30),
		KP_OCTAL = 219 | (1 << 30),
		KP_DECIMAL = 220 | (1 << 30),
		KP_HEXADECIMAL = 221 | (1 << 30),
		LCTRL = 224 | (1 << 30),
		LSHIFT = 225 | (1 << 30),
		LALT = 226 | (1 << 30),
		LGUI = 227 | (1 << 30),
		RCTRL = 228 | (1 << 30),
		RSHIFT = 229 | (1 << 30),
		RALT = 230 | (1 << 30),
		RGUI = 231 | (1 << 30),
		MODE = 257 | (1 << 30),
		AUDIONEXT = 258 | (1 << 30),
		AUDIOPREV = 259 | (1 << 30),
		AUDIOSTOP = 260 | (1 << 30),
		AUDIOPLAY = 261 | (1 << 30),
		AUDIOMUTE = 262 | (1 << 30),
		MEDIASELECT = 263 | (1 << 30),
		WWW = 264 | (1 << 30),
		MAIL = 265 | (1 << 30),
		CALCULATOR = 266 | (1 << 30),
		COMPUTER = 267 | (1 << 30),
		AC_SEARCH = 268 | (1 << 30),
		AC_HOME = 269 | (1 << 30),
		AC_BACK = 270 | (1 << 30),
		AC_FORWARD = 271 | (1 << 30),
		AC_STOP = 272 | (1 << 30),
		AC_REFRESH = 273 | (1 << 30),
		AC_BOOKMARKS = 274 | (1 << 30),
		BRIGHTNESSDOWN = 275 | (1 << 30),
		BRIGHTNESSUP = 276 | (1 << 30),
		DISPLAYSWITCH = 277 | (1 << 30),
		KBDILLUMTOGGLE = 278 | (1 << 30),
		KBDILLUMDOWN = 279 | (1 << 30),
		KBDILLUMUP = 280 | (1 << 30),
		EJECT = 281 | (1 << 30),
		SLEEP = 282 | (1 << 30),
		MOUSE4 = 283 | (1 << 30),
		MOUSE5 = 284 | (1 << 30)
	}

	public static class KeycodeExts
	{
		public static readonly IReadOnlyDictionary<Keycode, string> KeycodeFluentKeys = new Dictionary<Keycode, string>()
		{
			{ Keycode.UNKNOWN, "Keycode-Unknown" },
			{ Keycode.RETURN, "Keycode-Return" },
			{ Keycode.ESCAPE, "Keycode-Escape" },
			{ Keycode.BACKSPACE, "Keycode-Backspace" },
			{ Keycode.TAB, "Keycode-Tab" },
			{ Keycode.SPACE, "Keycode-Space" },
			{ Keycode.EXCLAIM, "Keycode-Exclaim" },
			{ Keycode.QUOTEDBL, "Keycode-Quotedbl" },
			{ Keycode.HASH, "Keycode-Hash" },
			{ Keycode.PERCENT, "Keycode-Percent" },
			{ Keycode.DOLLAR, "Keycode-Dollar" },
			{ Keycode.AMPERSAND, "Keycode-Ampersand" },
			{ Keycode.QUOTE, "Keycode-Quote" },
			{ Keycode.LEFTPAREN, "Keycode-Leftparen" },
			{ Keycode.RIGHTPAREN, "Keycode-Rightparen" },
			{ Keycode.ASTERISK, "Keycode-Asterisk" },
			{ Keycode.PLUS, "Keycode-Plus" },
			{ Keycode.COMMA, "Keycode-Comma" },
			{ Keycode.MINUS, "Keycode-Minus" },
			{ Keycode.PERIOD, "Keycode-Period" },
			{ Keycode.SLASH, "Keycode-Slash" },
			{ Keycode.NUMBER_0, "Keycode-Number-0" },
			{ Keycode.NUMBER_1, "Keycode-Number-1" },
			{ Keycode.NUMBER_2, "Keycode-Number-2" },
			{ Keycode.NUMBER_3, "Keycode-Number-3" },
			{ Keycode.NUMBER_4, "Keycode-Number-4" },
			{ Keycode.NUMBER_5, "Keycode-Number-5" },
			{ Keycode.NUMBER_6, "Keycode-Number-6" },
			{ Keycode.NUMBER_7, "Keycode-Number-7" },
			{ Keycode.NUMBER_8, "Keycode-Number-8" },
			{ Keycode.NUMBER_9, "Keycode-Number-9" },
			{ Keycode.COLON, "Keycode-Colon" },
			{ Keycode.SEMICOLON, "Keycode-Semicolon" },
			{ Keycode.LESS, "Keycode-Less" },
			{ Keycode.EQUALS, "Keycode-Equals" },
			{ Keycode.GREATER, "Keycode-Greater" },
			{ Keycode.QUESTION, "Keycode-Question" },
			{ Keycode.AT, "Keycode-At" },
			{ Keycode.LEFTBRACKET, "Keycode-Leftbracket" },
			{ Keycode.BACKSLASH, "Keycode-Backslash" },
			{ Keycode.RIGHTBRACKET, "Keycode-Rightbracket" },
			{ Keycode.CARET, "Keycode-Caret" },
			{ Keycode.UNDERSCORE, "Keycode-Underscore" },
			{ Keycode.BACKQUOTE, "Keycode-Backquote" },
			{ Keycode.A, "Keycode-A" },
			{ Keycode.B, "Keycode-B" },
			{ Keycode.C, "Keycode-C" },
			{ Keycode.D, "Keycode-D" },
			{ Keycode.E, "Keycode-E" },
			{ Keycode.F, "Keycode-F" },
			{ Keycode.G, "Keycode-G" },
			{ Keycode.H, "Keycode-H" },
			{ Keycode.I, "Keycode-I" },
			{ Keycode.J, "Keycode-J" },
			{ Keycode.K, "Keycode-K" },
			{ Keycode.L, "Keycode-L" },
			{ Keycode.M, "Keycode-M" },
			{ Keycode.N, "Keycode-N" },
			{ Keycode.O, "Keycode-O" },
			{ Keycode.P, "Keycode-P" },
			{ Keycode.Q, "Keycode-Q" },
			{ Keycode.R, "Keycode-R" },
			{ Keycode.S, "Keycode-S" },
			{ Keycode.T, "Keycode-T" },
			{ Keycode.U, "Keycode-U" },
			{ Keycode.V, "Keycode-V" },
			{ Keycode.W, "Keycode-W" },
			{ Keycode.X, "Keycode-X" },
			{ Keycode.Y, "Keycode-Y" },
			{ Keycode.Z, "Keycode-Z" },
			{ Keycode.CAPSLOCK, "Keycode-Capslock" },
			{ Keycode.F1, "Keycode-F1" },
			{ Keycode.F2, "Keycode-F2" },
			{ Keycode.F3, "Keycode-F3" },
			{ Keycode.F4, "Keycode-F4" },
			{ Keycode.F5, "Keycode-F5" },
			{ Keycode.F6, "Keycode-F6" },
			{ Keycode.F7, "Keycode-F7" },
			{ Keycode.F8, "Keycode-F8" },
			{ Keycode.F9, "Keycode-F9" },
			{ Keycode.F10, "Keycode-F10" },
			{ Keycode.F11, "Keycode-F11" },
			{ Keycode.F12, "Keycode-F12" },
			{ Keycode.PRINTSCREEN, "Keycode-Printscreen" },
			{ Keycode.SCROLLLOCK, "Keycode-Scrolllock" },
			{ Keycode.PAUSE, "Keycode-Pause" },
			{ Keycode.INSERT, "Keycode-Insert" },
			{ Keycode.HOME, "Keycode-Home" },
			{ Keycode.PAGEUP, "Keycode-Pageup" },
			{ Keycode.DELETE, "Keycode-Delete" },
			{ Keycode.END, "Keycode-End" },
			{ Keycode.PAGEDOWN, "Keycode-Pagedown" },
			{ Keycode.RIGHT, "Keycode-Right" },
			{ Keycode.LEFT, "Keycode-Left" },
			{ Keycode.DOWN, "Keycode-Down" },
			{ Keycode.UP, "Keycode-Up" },
			{ Keycode.NUMLOCKCLEAR, "Keycode-Numlockclear" },
			{ Keycode.KP_DIVIDE, "Keycode-Kp-Divide" },
			{ Keycode.KP_MULTIPLY, "Keycode-Kp-Multiply" },
			{ Keycode.KP_MINUS, "Keycode-Kp-Minus" },
			{ Keycode.KP_PLUS, "Keycode-Kp-Plus" },
			{ Keycode.KP_ENTER, "Keycode-Kp-Enter" },
			{ Keycode.KP_1, "Keycode-Kp-1" },
			{ Keycode.KP_2, "Keycode-Kp-2" },
			{ Keycode.KP_3, "Keycode-Kp-3" },
			{ Keycode.KP_4, "Keycode-Kp-4" },
			{ Keycode.KP_5, "Keycode-Kp-5" },
			{ Keycode.KP_6, "Keycode-Kp-6" },
			{ Keycode.KP_7, "Keycode-Kp-7" },
			{ Keycode.KP_8, "Keycode-Kp-8" },
			{ Keycode.KP_9, "Keycode-Kp-9" },
			{ Keycode.KP_0, "Keycode-Kp-0" },
			{ Keycode.KP_PERIOD, "Keycode-Kp-Period" },
			{ Keycode.APPLICATION, "Keycode-Application" },
			{ Keycode.POWER, "Keycode-Power" },
			{ Keycode.KP_EQUALS, "Keycode-Kp-Equals" },
			{ Keycode.F13, "Keycode-F13" },
			{ Keycode.F14, "Keycode-F14" },
			{ Keycode.F15, "Keycode-F15" },
			{ Keycode.F16, "Keycode-F16" },
			{ Keycode.F17, "Keycode-F17" },
			{ Keycode.F18, "Keycode-F18" },
			{ Keycode.F19, "Keycode-F19" },
			{ Keycode.F20, "Keycode-F20" },
			{ Keycode.F21, "Keycode-F21" },
			{ Keycode.F22, "Keycode-F22" },
			{ Keycode.F23, "Keycode-F23" },
			{ Keycode.F24, "Keycode-F24" },
			{ Keycode.EXECUTE, "Keycode-Execute" },
			{ Keycode.HELP, "Keycode-Help" },
			{ Keycode.MENU, "Keycode-Menu" },
			{ Keycode.SELECT, "Keycode-Select" },
			{ Keycode.STOP, "Keycode-Stop" },
			{ Keycode.AGAIN, "Keycode-Again" },
			{ Keycode.UNDO, "Keycode-Undo" },
			{ Keycode.CUT, "Keycode-Cut" },
			{ Keycode.COPY, "Keycode-Copy" },
			{ Keycode.PASTE, "Keycode-Paste" },
			{ Keycode.FIND, "Keycode-Find" },
			{ Keycode.MUTE, "Keycode-Mute" },
			{ Keycode.VOLUMEUP, "Keycode-Volumeup" },
			{ Keycode.VOLUMEDOWN, "Keycode-Volumedown" },
			{ Keycode.KP_COMMA, "Keycode-Kp-Comma" },
			{ Keycode.KP_EQUALSAS400, "Keycode-Kp-Equalsas400" },
			{ Keycode.ALTERASE, "Keycode-Alterase" },
			{ Keycode.SYSREQ, "Keycode-Sysreq" },
			{ Keycode.CANCEL, "Keycode-Cancel" },
			{ Keycode.CLEAR, "Keycode-Clear" },
			{ Keycode.PRIOR, "Keycode-Prior" },
			{ Keycode.RETURN2, "Keycode-Return2" },
			{ Keycode.SEPARATOR, "Keycode-Separator" },
			{ Keycode.OUT, "Keycode-Out" },
			{ Keycode.OPER, "Keycode-Oper" },
			{ Keycode.CLEARAGAIN, "Keycode-Clearagain" },
			{ Keycode.CRSEL, "Keycode-Crsel" },
			{ Keycode.EXSEL, "Keycode-Exsel" },
			{ Keycode.KP_00, "Keycode-Kp-00" },
			{ Keycode.KP_000, "Keycode-Kp-000" },
			{ Keycode.THOUSANDSSEPARATOR, "Keycode-Thousandsseparator" },
			{ Keycode.DECIMALSEPARATOR, "Keycode-Decimalseparator" },
			{ Keycode.CURRENCYUNIT, "Keycode-Currencyunit" },
			{ Keycode.CURRENCYSUBUNIT, "Keycode-Currencysubunit" },
			{ Keycode.KP_LEFTPAREN, "Keycode-Kp-Leftparen" },
			{ Keycode.KP_RIGHTPAREN, "Keycode-Kp-Rightparen" },
			{ Keycode.KP_LEFTBRACE, "Keycode-Kp-Leftbrace" },
			{ Keycode.KP_RIGHTBRACE, "Keycode-Kp-Rightbrace" },
			{ Keycode.KP_TAB, "Keycode-Kp-Tab" },
			{ Keycode.KP_BACKSPACE, "Keycode-Kp-Backspace" },
			{ Keycode.KP_A, "Keycode-Kp-A" },
			{ Keycode.KP_B, "Keycode-Kp-B" },
			{ Keycode.KP_C, "Keycode-Kp-C" },
			{ Keycode.KP_D, "Keycode-Kp-D" },
			{ Keycode.KP_E, "Keycode-Kp-E" },
			{ Keycode.KP_F, "Keycode-Kp-F" },
			{ Keycode.KP_XOR, "Keycode-Kp-Xor" },
			{ Keycode.KP_POWER, "Keycode-Kp-Power" },
			{ Keycode.KP_PERCENT, "Keycode-Kp-Percent" },
			{ Keycode.KP_LESS, "Keycode-Kp-Less" },
			{ Keycode.KP_GREATER, "Keycode-Kp-Greater" },
			{ Keycode.KP_AMPERSAND, "Keycode-Kp-Ampersand" },
			{ Keycode.KP_DBLAMPERSAND, "Keycode-Kp-Dblampersand" },
			{ Keycode.KP_VERTICALBAR, "Keycode-Kp-Verticalbar" },
			{ Keycode.KP_DBLVERTICALBAR, "Keycode-Kp-Dblverticalbar" },
			{ Keycode.KP_COLON, "Keycode-Kp-Colon" },
			{ Keycode.KP_HASH, "Keycode-Kp-Hash" },
			{ Keycode.KP_SPACE, "Keycode-Kp-Space" },
			{ Keycode.KP_AT, "Keycode-Kp-At" },
			{ Keycode.KP_EXCLAM, "Keycode-Kp-Exclam" },
			{ Keycode.KP_MEMSTORE, "Keycode-Kp-Memstore" },
			{ Keycode.KP_MEMRECALL, "Keycode-Kp-Memrecall" },
			{ Keycode.KP_MEMCLEAR, "Keycode-Kp-Memclear" },
			{ Keycode.KP_MEMADD, "Keycode-Kp-Memadd" },
			{ Keycode.KP_MEMSUBTRACT, "Keycode-Kp-Memsubtract" },
			{ Keycode.KP_MEMMULTIPLY, "Keycode-Kp-Memmultiply" },
			{ Keycode.KP_MEMDIVIDE, "Keycode-Kp-Memdivide" },
			{ Keycode.KP_PLUSMINUS, "Keycode-Kp-Plusminus" },
			{ Keycode.KP_CLEAR, "Keycode-Kp-Clear" },
			{ Keycode.KP_CLEARENTRY, "Keycode-Kp-Clearentry" },
			{ Keycode.KP_BINARY, "Keycode-Kp-Binary" },
			{ Keycode.KP_OCTAL, "Keycode-Kp-Octal" },
			{ Keycode.KP_DECIMAL, "Keycode-Kp-Decimal" },
			{ Keycode.KP_HEXADECIMAL, "Keycode-Kp-Hexadecimal" },
			{ Keycode.LCTRL, "Keycode-Lctrl" },
			{ Keycode.LSHIFT, "Keycode-Lshift" },
			{ Keycode.LALT, "Keycode-Lalt" },
			{ Keycode.LGUI, "Keycode-Lgui" },
			{ Keycode.RCTRL, "Keycode-Rctrl" },
			{ Keycode.RSHIFT, "Keycode-Rshift" },
			{ Keycode.RALT, "Keycode-Ralt" },
			{ Keycode.RGUI, "Keycode-Rgui" },
			{ Keycode.MODE, "Keycode-Mode" },
			{ Keycode.AUDIONEXT, "Keycode-Audionext" },
			{ Keycode.AUDIOPREV, "Keycode-Audioprev" },
			{ Keycode.AUDIOSTOP, "Keycode-Audiostop" },
			{ Keycode.AUDIOPLAY, "Keycode-Audioplay" },
			{ Keycode.AUDIOMUTE, "Keycode-Audiomute" },
			{ Keycode.MEDIASELECT, "Keycode-Mediaselect" },
			{ Keycode.WWW, "Keycode-Www" },
			{ Keycode.MAIL, "Keycode-Mail" },
			{ Keycode.CALCULATOR, "Keycode-Calculator" },
			{ Keycode.COMPUTER, "Keycode-Computer" },
			{ Keycode.AC_SEARCH, "Keycode-Ac-Search" },
			{ Keycode.AC_HOME, "Keycode-Ac-Home" },
			{ Keycode.AC_BACK, "Keycode-Ac-Back" },
			{ Keycode.AC_FORWARD, "Keycode-Ac-Forward" },
			{ Keycode.AC_STOP, "Keycode-Ac-Stop" },
			{ Keycode.AC_REFRESH, "Keycode-Ac-Refresh" },
			{ Keycode.AC_BOOKMARKS, "Keycode-Ac-Bookmarks" },
			{ Keycode.BRIGHTNESSDOWN, "Keycode-Brightnessdown" },
			{ Keycode.BRIGHTNESSUP, "Keycode-Brightnessup" },
			{ Keycode.DISPLAYSWITCH, "Keycode-Displayswitch" },
			{ Keycode.KBDILLUMTOGGLE, "Keycode-Kbdillumtoggle" },
			{ Keycode.KBDILLUMDOWN, "Keycode-Kbdillumdown" },
			{ Keycode.KBDILLUMUP, "Keycode-Kbdillumup" },
			{ Keycode.EJECT, "Keycode-Eject" },
			{ Keycode.SLEEP, "Keycode-Sleep" },
			{ Keycode.MOUSE4, "Keycode-Mouse4" },
			{ Keycode.MOUSE5, "Keycode-Mouse5" },
		};

		public static string DisplayString(Keycode k)
		{
			if (!KeycodeFluentKeys.TryGetValue(k, out var fluentKey))
				return k.ToString();

			return Game.Translate(fluentKey);
		}
	}
}
